[build-system]
requires = ["setuptools>=42"]
build-backend = "setuptools.build_meta"

[tool.semantic_release]
version_variable = [
    'src/mypackage/__init__.py:__version__',
]
version_source = "tag"
repository_url = "https://test.pypi.org/"
